---
title: "My First Plotty Plot"
author: "Kike Sedes"
date: "15 April 2020"
output: html_document
---

\fontfamily{cmr}
\fontsize{8}{12}
\selectfont

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Week 3 Assignment
In the next chunk of code, I will create a map with some data about COVID-19 positive cases. You can find latest data in this Github:https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv.

```{r fig.width=12, fig.height=8, comment="", results=FALSE, echo=TRUE, message=FALSE}
library(dplyr)
library(data.table)
library(plotly)
```
```{r fig.width=12, fig.height=8, comment=""}
data<-fread("time_series_covid19_confirmed_global.csv", sep=",")

#Get Data that we are going to plot
dataForMap = data %>% select(1,2,3,4,tail(names(.), 3))

#New ColNames for our dataset
newNames <- c("state", "country", "Lat", "Long", "Day1", "Day2", "Day3")
setnames(dataForMap, newNames)

#Geo styling
g <- list(
    #projection = list(type = 'albers usa'),
    showland = TRUE,
    landcolor = toRGB("gray95"),
    subunitcolor = toRGB("gray85"),
    countrycolor = toRGB("gray85"),
    countrywidth = 0.5,
    subunitwidth = 0.5
)

#Final Plot
fig <- plot_geo(dataForMap, lat = ~Lat, lon = ~Long)
fig <- fig %>% add_markers(
    text = ~paste(country, paste("Cod-19 Positives:", Day3), sep = "<br />"),
    color = ~Day3, symbol = I("square"), size = I(8), hoverinfo = "text"
)
fig <- fig %>% colorbar(title = "Positive Cases Cod19<br />February 2011")
fig <- fig %>% layout(
    title = 'Cod-19 per Country<br />(Hover for numbers)', geo = g
)

fig
```